# Generated by Django 4.0.6 on 2023-05-16 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_test_score_test_shortlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_shortlist',
            name='score',
        ),
    ]
