# Generated by Django 4.0.6 on 2023-05-16 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_remove_test_shortlist_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='final_shortlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=125)),
            ],
        ),
        migrations.AddField(
            model_name='test_shortlist',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='test_score',
            name='email',
            field=models.EmailField(max_length=125),
        ),
        migrations.AlterField(
            model_name='test_shortlist',
            name='email',
            field=models.EmailField(max_length=125),
        ),
    ]
